# Generated by Django 5.0.2 on 2024-04-05 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID сессии')),
                ('payment_sum', models.FloatField(default=1000, verbose_name='Сумма платежа')),
                ('payment_type', models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Перевод')], default='CASH', max_length=5, verbose_name='Тип оплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Оплата пользователя',
                'verbose_name_plural': 'Оплаты пользователя',
            },
        ),
    ]
